FROM python:3.12-slim

WORKDIR /app

COPY .venv .venv
ENV PYTHONPATH="/app/.venv/lib/python3.12/site-packages"

COPY set_a/evaluate.py .
COPY set_a/setA.pth .
COPY set_a/data/test/ data/test/

CMD ["python", "evaluate.py"]
